//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public long PatientID { get; set; }
        public string TCNo { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string History { get; set; }
        public Nullable<System.DateTime> DateOfInspection { get; set; }
        public string GSM { get; set; }
        public string Tel { get; set; }
        public string Adres { get; set; }
    }
}
